version: 2

dependencies:
  override:
  - echo y | android update sdk --no-ui --all --filter tools,platform-tools,android-23,extra-android-m2repository,extra-google-m2repository,extra-google-google_play_services,extra-android-support
  - echo y | android update sdk --no-ui --all --filter build-tools-23.0.3

test:
  override:
  # perform unit tests
  - ./gradlew tesMockDebugUnitTest
  # Save test reports
  - mkdir -p $CIRCLE_TEST_REPORTS/reports/unit-tests
  - cp -avr app/build/reports/tests/mockDebug/ $CIRCLE_TEST_REPORTS/reports/unit-tests
  - mkdir -p $CIRCLE_TEST_REPORTS/junit/
  - find . -type f -regex ".*/build/test-results/mockDebug/.*xml" -exec cp {} $CIRCLE_TEST_REPORTS/junit/ \;

  # start the emulator
  - emulator -avd circleci-android22 -no-audio -no-window:
      background: true
      parallel: true
  # wait for it to have booted
  - circle-android wait-for-boot
  # unlock the emulator screen
  - sleep 30
  - adb shell input keyevent 82
  # run tests against the emulator.
  - ./gradlew connectedMockDebugAndroidTest -PdisablePreDex
  # Copying the test reports
  - mkdir -p $CIRCLE_TEST_REPORTS/reports/functional-tests
  - cp -avr app/build/reports/androidTests/connected/flavors/MOCK/ $CIRCLE_TEST_REPORTS/reports/functional-tests

jobs:
  build:
    working_directory: ~/code
    docker:
    - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
    - checkout
    - restore_cache:
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    - run:
        name: Download Dependencies
        command: ./gradlew androidDependencies
    - save_cache:
        paths:
        - ~/.gradle
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    - store_artifacts:
        path: app/build/reports
        destination: reports
    - store_test_results:
        path: app/build/test-results